---
- name: Backup junos configurations
  hosts: junos 
  gather_facts: false
  connection: network_cli

  vars:
    ansible_network_os: ios

  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars
      delegate_to: localhost

  tasks:
    - name: Set file operations facts
      ansible.builtin.set_fact:
        tmp_config_store: "{{ root_dir }}/{{ config_backup_file }}"
        git_repo_vendor_dir: "{{ junos_git_repo_dir }}"
      delegate_to: localhost

    - name: Import role-junos-config-backup role
      ansible.builtin.import_role:
        name: role-junos-config-backup
      vars:
        junos: true