---
- name: UPLOAD OS IMAGE FILE TO JUNIPER DEVICE
  hosts: "{{ target_host }}"
  gather_facts: no
  connection: ansible.netcommon.netconf
  
  vars:
    ansible_network_os: junos
    ansible_port: 22  # Quite a number of devices can't be reached on default port 830
    ansible_ssh_timeout: "3600" # Ample time for uploads to take place
    junos_provider:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      timeout: "{{ junos_sw_upgrade_timeout }}"
 
  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars

  tasks:
    - name: Debug extra variables
      ansible.builtin.debug:
        msg:
          - "Hostname      : {{ target_host }}"
          - "OS Image File : {{ os_image_file }}"
      delegate_to: localhost

    - name: Import role-juniper-software
      ansible.builtin.include_role:
        name: role-juniper-software
      vars:
        _upload_: true
        _upgrade_: false
        _software_image_file_name_: "{{ os_image_file  }}"
        _software_image_file_source_: "{{ tmp_base_dir }}/{{ os_image_file }}"
        _juniper_device_hostname_: "{{ target_host }}"
        _juniper_device_file_dir_: "{{ junos_device_storage_path }}"
        _provider_: "{{ junos_provider }}"
        

- name: PERFORM SOFTWARE UPGRADE
  hosts: "{{ target_host }}"
  gather_facts: false
  connection: ansible.netcommon.netconf
  
  vars:
    ansible_network_os: junos
    ansible_port: 22  # Quite a number of devices can't be reached on default port 830
    junos_provider:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      timeout: "{{ junos_sw_upgrade_timeout }}"
      
  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars
      delegate_to: localhost

  tasks:
    - name: Debug extra variables
      ansible.builtin.debug:
        msg:
          - "Hostname      : {{ target_host }}"
          - "OS Image File : {{ os_image_file }}"
      delegate_to: localhost
    
    - name: Import role-juniper-software
      ansible.builtin.include_role:
        name: role-juniper-software
      vars:
        _upload_: false
        _upgrade_: true
        _software_image_file_name_: "{{ os_image_file  }}"
        _software_image_file_source_: "{{ tmp_base_dir }}/{{ os_image_file }}"
        _juniper_device_hostname_: "{{ target_host }}"
        _juniper_device_file_dir_: "{{ junos_device_storage_path }}"
        _provider_: "{{ junos_provider }}"