---
# dual routing engine upgrade tasks

- name: dual routing engine test task
  ansible.builtin.debug:
    msg:
      - "Device has dual routing engines."
  ignore_errors: true
  delegate_to: localhost