---
# Collect Junos facts
- name: Gather Junos-specific facts
  junipernetworks.junos.junos_facts:
    gather_subset:
      - hardware        # Hardware-related facts like chassis info
      - config         # Configuration information
      #- interfaces     # Interface details
      - default         # default values
  register: junos_facts

- name: Display gathered Junos facts
  ansible.builtin.debug:
    var: junos_facts.ansible_facts

# - name: Display ansible_net_has_2RE value
#   ansible.builtin.debug:
#     var: junos_facts.ansible_facts["ansible_net_has_2RE"]

# - name: Display ansible_net_version value
#   ansible.builtin.debug:
#     var: junos_facts.ansible_facts["ansible_net_version"]

- name: Set current_os_version
  ansible.builtin.set_fact:
    current_os_version: "{{ junos_facts.ansible_facts['ansible_net_version'] }}"
  delegate_to: localhost

- name: Display current version
  ansible.builtin.debug:
    msg: 
      - "Current OS version = {{ current_os_version }}"
