---
# Main tasks
- name: Import upload software image tasks
  ansible.builtin.import_tasks: upload.yml
  when: 
    - upgrade_device == false
    - upload_image

- name: Import upgrade_device tasks
  ansible.builtin.import_tasks: upgrade.yml
  when: 
    - upgrade_device
    - upload_image == false

