---
# single routing engine upgrade tasks

- name: single routing engine test task
  ansible.builtin.debug:
    msg:
      - "Device has single routing engine."
  ignore_errors: true
  delegate_to: localhost

# - name: install local package on remote device
#   junipernetworks.junos.junos_package:
#     src: "{{ juniper_device_tmp_storage }}/{{ software_image_file_name }}"
#     no_copy: true
#     # host: "{{ inventory_hostname }}"
#   register: upgrade

## pull down junos-exec-env from quay.io and confirm the story of modules missing!
## This shit has to work within Wed!!
## Keep buying time with dual-re devices for testing though!..ha ha ha

- name: Upgrade Junos OS from package copied at device
  juniper.device.software:
    host: "{{ inventory_hostname }}"
    user: "{{ ansible_user }}"
    passwd: "{{ ansible_password }}"
    remote_package: "{{ juniper_device_tmp_storage }}/{{ software_image_file_name }}"
    no_copy: true
    cleanfs: false
    validate: true
  register: response


- name: Debug upgrade results
  ansible.builtin.debug:
    var: upgrade
