---
# 1. Confirm image is already uploaded on the device
# - name: List files on the device
#   junipernetworks.junos.junos_command:
#     commands: "file list {{ juniper_device_tmp_storage }}"
#   register: file_list
#   ignore_errors: true

- name: "Execute command with login credentials"
  juniper.device.command:
    host: "{{ inventory_hostname }}"
    user: "{{ ansible_user }}"
    passwd: "{{ ansible_password }}"
    commands:
      - "file list {{ juniper_device_tmp_storage }}"
  register: file_list

- name: Debug upload result
  ansible.builtin.debug:
    var: file_list["stdout_lines"][0]
  delegate_to: localhost
  ignore_errors: true

- name: "Assert {{ software_image_file_name }} exists on the Juniper device - FAIL Playbook if NOT existing"
  ansible.builtin.assert:
    that:
      - software_image_file_name in file_list.stdout[0]
    fail_msg: "{{ software_image_file_name }} does not exist on Juniper device. Playbook stopped"
    success_msg: "{{ software_image_file_name }} exists on Juniper device. Proceeding with the next tasks."
  delegate_to: localhost

# 2. Determine device is single or dual routing engine
- name: Gather Junos-specific facts
  junipernetworks.junos.junos_facts:
    gather_subset:
      - hardware        # Hardware-related facts like chassis info
      #- config         # Configuration information
      #- interfaces     # Interface details
      - default         # default values
  register: junos_facts

# - name: Display gathered Junos facts
#   ansible.builtin.debug:
#     var: junos_facts.ansible_facts

- name: Display ansible_net_has_2RE value
  ansible.builtin.debug:
    var: junos_facts.ansible_facts["ansible_net_has_2RE"]


# 3. Perform software upgrade

# dual routing engines
- block:
     # dual routing engine upgrade tasks
     ## Need to write this logic!!

    - name: dual routing engine test task
      ansible.builtin.debug:
        msg:
          - "Device has dual routing engines."
      ignore_errors: true
      delegate_to: localhost
      

  when: junos_facts.ansible_facts["ansible_net_has_2RE"]
  
  

# single routing engines
- block:
     # single routing engine upgrade tasks

    - name: single routing engine test task
      ansible.builtin.debug:
        msg:
          - "Device has single routing engine."
      ignore_errors: true
      delegate_to: localhost

    # - name: install local package on remote device
    #   junipernetworks.junos.junos_package:
    #     src: "{{ juniper_device_tmp_storage }}/{{ software_image_file_name }}"
    #     no_copy: true
    #     # host: "{{ inventory_hostname }}"
    #   register: upgrade

    - name: Upgrade Junos OS from package copied at device
      juniper.device.software:
        host: "{{ inventory_hostname }}"
        user: "{{ ansible_user }}"
        passwd: "{{ ansible_password }}"
        remote_package: "{{ juniper_device_tmp_storage }}/{{ software_image_file_name }}"
        no_copy: true
        cleanfs: false
        validate: true
      register: response

    - name: Debug upgrade results
      ansible.builtin.debug:
        var: upgrade

  when: junos_facts.ansible_facts["ansible_net_has_2RE"] == false