---
# Step 1 : Collect device ansible facts to determine if dual routing engine or not
# Step 2 : Perform upgrade steps based on the above

- name: Gather Junos-specific facts
  junipernetworks.junos.junos_facts:
    gather_subset:
      - hardware        # Hardware-related facts like chassis info
      #- config         # Configuration information
      #- interfaces     # Interface details
      - default         # default values
  register: junos_facts

# - name: Display gathered Junos facts
#   ansible.builtin.debug:
#     var: junos_facts.ansible_facts

- name: Display ansible_net_has_2RE value
  ansible.builtin.debug:
    var: junos_facts.ansible_facts["ansible_net_has_2RE"]


# Tasks for devices with dual Routing Engines
- block:
    - name: dual routing engine test task
      ansible.builtin.debug:
        msg:
          - "Device has dual routing engines."
      ignore_errors: true
      delegate_to: localhost

  when: junos_facts.ansible_facts["ansible_net_has_2RE"]

# Tasks for devices with a single Routing Engine
- block:
    - name: single routing engine test task
      ansible.builtin.debug:
        msg:
          - "Device has single routing engine."
      ignore_errors: true
      delegate_to: localhost


  when: junos_facts.ansible_facts["ansible_net_has_2RE"] == false