---
# Uploading software image to the device

# Step 1 : Download OS image from the artifacts store (gitlab in this case) and upload to device
- name: Clone the os images git artifacts
  ansible.builtin.git:
    repo: "{{ git_repo_url }}"
    dest: "{{ tmp_root_dir }}/{{ git_repo_name }}"
    version: "{{ git_repo_branch }}"
    force: yes       # Still clone down and overwrite incase local repo is existing.
  ignore_errors: true
  run_once: true
  delegate_to: localhost

- name: Set facts
  ansible.builtin.set_fact:
    sw_image_file_path: "{{ tmp_root_dir }}/{{ git_repo_name }}/{{ vendor_dir }}/{{ software_image_file_name }}"
  delegate_to: localhost

- name: "Check if {{ software_image_file_name }} exists on the local"
  ansible.builtin.stat:
    path: "{{ sw_image_file_path }}"
  register: file_check 
  delegate_to: localhost
  ignore_errors: true
    
- name: "Assert {{ software_image_file_name }} exists on the local - FAIL Playbook if NOT existing"
  ansible.builtin.assert:
    that:
      - file_check.stat.exists
    fail_msg: "{{ software_image_file_name }} does not exist on local. Playbook stopped"
    success_msg: "{{ software_image_file_name }} exists on local. Proceeding with the next tasks."
  delegate_to: localhost


# Step 2 : Upload image to the device

# - name: Check if image already existing on the device # Will it matter? Unless we worry about space?

- name: Upload OS image to the Juniper device
  junipernetworks.junos.junos_scp:
    src: "{{ sw_image_file_path }}"
    dest: "{{ juniper_device_tmp_storage }}"
    timeout: 1800 # Is 1 hr an overkill?
  register: upload_result

- name: Debug upload result
  ansible.builtin.debug:
    var: upload_result