---
# Upload file to juniper device from Ansible Controller

- name: "upload {{ _software_image_file_name_ }} to {{ _juniper_device_file_dir_ }} directory on {{ juniper_device_hostname }}"
  junipernetworks.junos.junos_scp:
    src: "{{ _software_image_file_source_ }}"
    dest: "{{ _juniper_device_file_dir_ }}"
    remote_src: false
    provider: "{{ _provider_ }}"

# Confirm image is already uploaded on the device
- name: List files on the device
  junipernetworks.junos.junos_command:
    commands: "file list {{ _juniper_device_file_dir_ }}"
  register: file_list
  ignore_errors: true

# - name: Debug file_list
#   ansible.builtin.debug:
#     var: file_list["stdout_lines"][0]
#   delegate_to: localhost
#   ignore_errors: true

- name: "Assert {{ _software_image_file_name_ }} exists on the {{ _juniper_device_hostname_ }} - FAIL Playbook if NOT existing"
  ansible.builtin.assert:
    that:
      - _software_image_file_name_ in file_list.stdout[0]
    fail_msg: "{{ _software_image_file_name_ }} does not exist on {{ _juniper_device_hostname_ }}. Playbook stopped"
    success_msg: "{{ _software_image_file_name_ }} exists on {{ _juniper_device_hostname_ }}. Proceeding with the next tasks."
  delegate_to: localhost
  ignore_errors: true # You want the role to run end to end